### ISSUE TITLE
Console 请求错误

### ISSUE THREAD

**Issue by CodeAlmas** [longgeek/bug-report#152]
新用户进学习界面时docker 400错误.

换个账号登录没问题！

错误:
## 400 Bad Request

nginx

**Comment by longgeek** [comment]
找到了 Nginx 的 log， 如下:

```
2015/03/31 21:48:33 [error] 2864#0: *119372 [lua] access_by_lua(nginx.conf:134):22: no host found for key http://4ac9a85ad43eb5e26cd1a888.console.pythonpie.com, client: 119.122.82.155, server: *.console.pythonpie.com, request: "GET / HTTP/1.1", host: "4ac9a85ad43eb5e26cd1a888.console.pythonpie.com", referrer: "http://www.pythonpie.com/online/study/"
```

待分析.

**Comment by longgeek** [comment]
大致原因由于 Nginx 连接时间造成，当用户停留在任何 console 界面没有操作 15 分钟后，Nginx 就会断开连接。现在前端 Socket 默认为 2 小时，正在修改 Nginx 连接时间，还需要测试。

**Comment by longgeek** [comment]
up 15 minutes to 2 hours：

```
http://review.pyindex.com/#/c/1604/
http://review.pyindex.com/#/c/1605/
```

**Comment by hajifish** [comment]
Testing and Check

**Comment by longgeek** [comment]
zion 的问题，zion 会出现 Socket 连接丢失，导致容器 stop，在 stop 过程中会在 redis 中删除 console 对应的 value，而前端还是那个 value 地址，去请求 nginx，才会出现 400 err。

**Comment by hajifish** [comment]
应该不全是 zion 的， nginx 这边是怎么保持链接的， 是否能在优化下？

------------------ Original ------------------

**Comment by longgeek** [comment]
@xcluo 现在没有用 nginx，直接启动的 zion 守护进程。

**Comment by hajifish** [comment]
好的

**Comment by longgeek** [comment]
zion 使用了独立 Nginx 后，经过一天的测试，没有在出现 400 错误，现在临时关闭，后期再出现可以重新打开。

**Comment by hajifish** [comment]
Well done!
