### ISSUE TITLE
还要看本章内容

### ISSUE THREAD

**Issue by CodeAlmas** [longgeek/bug-report#154]
本章完毕之后，我觉得我还是想看看本章。

**Comment by CodeAlmas** [comment]
不点击 进入下一节， 直接刷新就可以回到上一个task

加一个刷新按钮.

**Comment by longgeek** [comment]
@almasgeek 不需要在加按钮了吧，可以点击上面的 Dot 按钮来跳转或再次学习。

**Comment by hajifish** [comment]
agree with @longgeek              已经存在入口了，就不要再加太多 按钮
