### ISSUE TITLE
[Looker]学习过程中，经常出现如下界面，发生500错误

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#155]
![2015-03-31 9 41 35](https://cloud.githubusercontent.com/assets/2637585/6920717/ca8b99b4-d7f2-11e4-8628-afa56742c650.png)

**Comment by longgeek** [comment]
@baoyiluo 是否在 task 或 stage 跳转过程中抛出的这个 500 错误？

**Comment by longgeek** [comment]
@xcluo 出现这种情况的原因是？

**Comment by hajifish** [comment]
看情况时  session 被删除了， 可能还是和 那个 session  机制有关系， @frazy 关闭 你那段 代码， 未知因素太多，暂不开放重新登录功能。

另外为了方便用户再次登陆， @almasgeek  在 boss 界面开发一个用户管理功能， 在用户通过 qq 提交相关问题后，我们手动帮助 删除 session 

我重新提交了一个issue， 已经分配给 @almasgeek  了。

**Comment by hajifish** [comment]
诶， 好像不是， 看截图， session 的 current_course_pk 存在， 但是 current_part_pk 不存在，可能是业务流程有问题， 我确认下。

**Comment by hajifish** [comment]
@baoyiluo 你把操作过程在细致截图下。thx

**Comment by baoyiluo** [comment]
学习过程中突然页面卡住了。然后刷新页面就会出现上面的问题

**Comment by hajifish** [comment]
应该还是之前问题影响，看已解决的代码是否能 消除这个问题。

**Comment by hajifish** [comment]
Done
