### ISSUE TITLE
Boss 增加用户管理功能

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#158]
列出用户，删除登陆状态

增加一个新的一级菜单，在工单和cloud之间。

里面一个页面：“用户管理”， 每个用户后面有个按钮，“删除登陆”。

有类似提交，已经关闭，但有详细说明：https://github.com/THSTACK/bug-report/issues/124

**Comment by baoyiluo** [comment]
删除登录状态，会造成计费的错误

**Comment by hajifish** [comment]
Please define workflow, and named:

In: workflow/auth/user.py

def clear_user():
    """Clear user data

```
Workflow:
    1. Clear Learning data, in XXXXXXX model
    2. Clear Billing data, in XXXXXXXX model """
```

def delete_user():
    """Delete user.

```
Workflow: 
     1. 
"""
```

**Comment by hajifish** [comment]
@longgeek 提供了手动删除脚本，Done.
