### ISSUE TITLE
[Looker]学习完课程点击继续学习bug

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#160]
![2015-04-01 11 40 48](https://cloud.githubusercontent.com/assets/2637585/6934245/f5d1476a-d863-11e4-995f-6dd1037b3f4b.png)
![2015-04-01 11 36 10](https://cloud.githubusercontent.com/assets/2637585/6934248/ffe2d66a-d863-11e4-8a2b-a60d6847e2f3.png)
![2015-04-01 11 41 02](https://cloud.githubusercontent.com/assets/2637585/6934536/f7904e7a-d868-11e4-8bc9-a2126c6a49ac.png)

**Comment by longgeek** [comment]
@baoyiluo 记得加一下 tags

**Comment by hajifish** [comment]
Done: http://review.pyindex.com/#/c/1618/
