### ISSUE TITLE
用户密码无法重置

### ISSUE THREAD

**Issue by baxiaoshi** [longgeek/bug-report#163]
用户密码/邮箱无法重置，输入完后，点击重置没反映。

**Comment by longgeek** [comment]
@baxiaoshi 我们收到你了提交的反馈，我们这就安排人员去测试。非常感谢。

**Comment by baoyiluo** [comment]
@baxiaoshi 非常感谢您提交bug，初步确认为原始密码输入不正确,没有提示！bug已确认，我们会尽快修复！

**Comment by longgeek** [comment]
@baxiaoshi 已确认是 Bug，已加 Confirmed 标签，我们正在修复中，再次感谢。

**Comment by longgeek** [comment]
Reset Password Fixed Bug:

```
http://review.pyindex.com/#/c/1632/
```

**Comment by longgeek** [comment]
密码功能 Bug 已修复，邮箱功能正在解决。

**Comment by longgeek** [comment]
Reset Email Fixed Bug:

```
http://review.pyindex.com/#/c/1636/
```
