### ISSUE TITLE
我的配置中大小不一样

### ISSUE THREAD

**Issue by vincenthe11** [longgeek/bug-report#164]
上月账单大小和其他格式大小不一样

**Comment by longgeek** [comment]
补一下图:

![image](https://cloud.githubusercontent.com/assets/2102615/6941932/61fa29fa-d8b6-11e4-864e-6b3ec56c0fa6.png)

多谢 @hewenhong 的反馈，我们会马上解决。

**Comment by longgeek** [comment]
commited, the reviewing:

```
http://review.pyindex.com/#/c/1634/1
```
