### ISSUE TITLE
注册时候发送邮箱的BUG

### ISSUE THREAD

**Issue by dilyar507** [longgeek/bug-report#169]
注册的时候系统自动发送的邮箱有BUG 打开的链接 不能访问

**Comment by longgeek** [comment]
补图：
![image](https://cloud.githubusercontent.com/assets/2102615/6963136/0122833a-d96e-11e4-988c-39bb6881a95e.png)

**Comment by longgeek** [comment]
已确认 Bug，交由 @baoyiluo 去修复。

**Comment by hajifish** [comment]
Merged, waiting push into online

**Comment by longgeek** [comment]
pulled
