### ISSUE TITLE
没登录，直接点击开始，无任何反应

### ISSUE THREAD

**Issue by vincenthe11** [longgeek/bug-report#171]
Remote Address:42.62.101.180:80
Request URL:http://pythonpie.com/online/start/
Request Method:GET
Status Code:302 FOUND

**Comment by longgeek** [comment]
@hewenhong 经过测试，没有发现这个问题。
会直接跳转到 http://pythonpie.com/auth/sign_in/ 登陆界面

**Comment by longgeek** [comment]
右上角的开始不跳转到登录界面，绿色的开始可以跳转：

![image](https://cloud.githubusercontent.com/assets/2102615/6964843/7d73efb2-d97f-11e4-832d-56ecda1350e8.png)

**Comment by longgeek** [comment]
和 session 有关联，分配给 @xcluo 来 fix

**Comment by hajifish** [comment]
判定 request.session.current_course_pk 是否存在，如果没有存在则提示 "你还没有选择一个课程，请先选择一个课程进入。“ 可以使用类似于 html title 属性，但是title 太慢，考虑别的类似方式 @baoyiluo 

i18n:

You have not chosen a course, please select one to enter first!

**Comment by baoyiluo** [comment]
未登录状态，不应该直接跳转登录界面？

**Comment by hajifish** [comment]
用户需要看看大纲 在决定是否注册/登陆

**Comment by vincenthe11** [comment]
不是，我是说，点击开始，需要跳转到登录。这个bug是不跳转
