### ISSUE TITLE
没登录用户，点击快速编程体验按钮，无反应，体验不好

### ISSUE THREAD

**Issue by yuanmingpeng** [longgeek/bug-report#172]
目前没有登录时，快速编程体验按钮鼠标经过是可点击状态，但是点击没有响应，容易使用户造成疑惑。
建议点击以上按钮跳转到登录页面，或是将”快速编程体验“按钮限制不可点击。
![pythonpie](https://cloud.githubusercontent.com/assets/11782200/6979249/a157e156-da13-11e4-80cf-7954251bb8ee.png)

**Comment by longgeek** [comment]
@yuanmingpeng hi, 非常感谢你的反馈, 我们已确认这个 Bug，稍后马上就会修复，敬请关注。

**Comment by hajifish** [comment]
Done        没登陆跳转到登陆窗口，登陆后就可以进入了。
