### ISSUE TITLE
[Looker]选择题样式正确答案，我的答案挡题目内容

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#173]
![2015-04-03 6 20 26](https://cloud.githubusercontent.com/assets/2637585/6981130/5b5922c0-da2f-11e4-8b98-17e19da3c812.png)

**Comment by baoyiluo** [comment]
查看我的答案，正确答案和对应的题操作上我觉得很绕,如果题多的话，会被绕晕吧？第一时间不能确定那道题错误。切换起来还得来回的移动鼠标。

**Comment by longgeek** [comment]
same https://github.com/THSTACK/bug-report/issues/190
