### ISSUE TITLE
[Looker]stage最后一道题，跳过无效

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#174]
![2015-04-03 8 31 04](https://cloud.githubusercontent.com/assets/2637585/6982309/a57723c6-da42-11e4-813c-961dfbab3a72.png)

![2015-04-03 8 31 04](https://cloud.githubusercontent.com/assets/2637585/6982309/a57723c6-da42-11e4-813c-961dfbab3a72.png)

**Comment by hajifish** [comment]
Done, 需前端判定

**Comment by longgeek** [comment]
@xcluo 现在关于 BACK 和 SKIP 的代码计算量非常复杂，而 SKIP 和 God it 又有关联，我在想是否可以去掉 BACK 和 SKIP，让用户完全依赖顶部的 Dot 按钮来跳转, 页面也会显得比较简洁.

**Comment by hajifish** [comment]
根据群里面的讨论，大家刚开始都不知道上面的 dot 能用。 如果去掉，过于简单了，并且感觉没有那种流畅感，鼠标还需要跳来跳去。我倒是想重新封装一下逻辑，让按钮就是按钮，把所有action都bind化，通过bind, unbind来控制，就能简化了。你觉得如何？

------------------ Original ------------------

**Comment by longgeek** [comment]
用户刚开始不知道 Dot 能用，最主要是鼠标移到 Dot 上没有相应的 task 名字显示，我们把 hover 做的明显一点，这样用户可能就会点击 Dot 选择性的去学习，一般一个 stage 里有很多 task，用户点击 skip 跳来跳去，其实还是看 Dot 来知道自己在第几个 task 上。

去掉 back、skip 唯一一点缺陷就是鼠标移动距离远一点。

**Comment by CodeAlmas** [comment]
http://www.jq22.com/Demo2576

back和skip 去掉， 
像这个效果类似，鼠标移动到要跳转的task是 ， 两边的圆圈进去， 而选中的 放大展示，task的名！

个人想法!

**Comment by hajifish** [comment]
这么大，往哪里放，缩小了了有没感觉了。

------------------ Original ------------------

**Comment by hajifish** [comment]
那就暂时这样了，不改了？新界面在设计，如何？同意就 close issue
