### ISSUE TITLE
Looker实时接受消息

### ISSUE THREAD

**Issue by CodeAlmas** [longgeek/bug-report#177]
looker 问答模块实时需要接受消息！

**Comment by baoyiluo** [comment]
消息包括：消费消息，新的回答消息。还有其他吗？@xcluo
用户点击消息，展开消息界面。消息归0.

**Comment by hajifish** [comment]
消息类型 不要固定，要灵活一些，适应无法预知的增加。

就用户处理消息的体验，不仅仅是 点击，展开，归零，还需要考虑：
    1. 消息在不同环境，比如在 index, boot,study等页面的提示方式和效果是否能一致？不能一致怎么办，后面新界面会有什么好的影响和需要提前准备/注意的事项；
    2. 消息的展示：来源不同的消息如何展示，比如从邮件来的，比如从消息通知来的，比如在study收到的问答消息又该如何？这些就算不能统一到一样的展示方式，那能否在后端方面统一起来，在前端方面灵活一些，方便修改升级
    3. 消息的处理：对于计费消息，是关闭之还是删除之，对于通知消息，又如何处理？
    4. 另外，根据昨天QQ群用户激烈争论的焦点，在实时和质量直接如何平衡，问答(工单）系统是否考虑一些锁机制，这些机制同样影响消息的展示和提示，具体可以查阅QQ群测试用户的讨论。

就以上问题， 研究下。
