### ISSUE TITLE
发邮件模板统一起来！

### ISSUE THREAD

**Issue by CodeAlmas** [longgeek/bug-report#178]
boss & looker  很多模块使用发送邮件功能！
根据邮件内容邮件模板需要统一起来！

**Comment by CodeAlmas** [comment]
1.looker 学生提问题,boss接受问题时 邮件发送给对应课程的组织老师(在boss查看).
2.老师回答问题时，邮件发送给学生.(邮件内容包含问题的答案，和问题连接地址)

**Comment by hajifish** [comment]
这个流程还需要在细化

比如： 邮件发送的内容。

还有， 你们现在这个 发送， 邮件头 怎么还是酒写了个 "titcket", 不是说写  
问题的 title或content 吗?

在 15/4/7 下午1:18, Almas 写道:

> 1.looker 学生提问题,boss接受问题时 邮件发送给对应课程的组织老师.
> 2.老师回答问题时，邮件发送给学生.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/THSTACK/bug-report/issues/178#issuecomment-90362734.

## 

全栈科技 ｜ ThStack Inc. Simon Luo | CEO & Founder of ThStack Inc. Mail: 
simonluo@thstack.com | xcluo@thstack.com Website: www.thstack.com 
--------------------------------------- Mysite: www.xcluo.com 
LiveStack(OpenStack Live OS): livestack.org OpenStack Demo(For Testing): 
cloud.thstack.com Training Center(Python, OpenStack, Hadoop): 
www.pythonpie.com OnlineCourse: online.pythonpie.com

**Comment by CodeAlmas** [comment]
Boss回复时给学生发邮件 邮件内容为:



hi,mail or username:
  你xxxx-xx-xx xx:xx:xx时，学xx课程遇到的问题有回答.

学生问题:xxxxxxxxx
老师回答:xxxxxxxxxx

**Comment by hajifish** [comment]
Good

**Comment by baoyiluo** [comment]
@almasgeek 邮件内容别忘了加问题的链接地址
