### ISSUE TITLE
怎么把我的本机文件传到虚拟机上？

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#179]
需要研究下
![2](https://cloud.githubusercontent.com/assets/1789545/7017444/0312d0c2-dd2a-11e4-9bb8-d3c3e9301875.png)

**Comment by longgeek** [comment]
@xcluo 开放 ssh 端口，让它可以直接 scp？

**Comment by longgeek** [comment]
@xcluo 我想完全开放 ssh，这也和咱们理念一直，用户可以通过 ssh root@ssh.username.console.pythonpie.com 来直接 ssh，最好省略一切参数。

要做到这样需要关注两点：
1.  nginx 转发 ssh 协议，貌似国人写了一个模块，不知是否复合我们的需求
2.  iptables，console.pythonpie.com 所在主机做 iptables 控制，用代码读取 redis key，拿到 Docker 主机地址和端口，在转发。

**Comment by hajifish** [comment]
TCP  cross  by Nginx well 

------------------ Original ------------------

**Comment by hajifish** [comment]
整个 /pythonpie/ 目录在 ftp 下，用户有其独立的 ftp 配置，比如： 

```
ftp://xcluo.console.pythonpie.com/
```

另外：需要用户名和密码保证私密性。

新架构下实现。
