### ISSUE TITLE
我在本机复制的，怎么粘贴到虚拟机？（多浏览器，多平台下）

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#180]
需要研究下：

![image](https://cloud.githubusercontent.com/assets/1789545/7017459/3f40e7e6-dd2a-11e4-84ef-2c699dc36569.png)

**Comment by longgeek** [comment]
@xcluo butterfly 的问题, https://github.com/paradoxxxzero/butterfly/issues/62

**Comment by hajifish** [comment]
类似  #179
