### ISSUE TITLE
课程优化

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#181]
![image](https://cloud.githubusercontent.com/assets/1789545/7017486/9845c76c-dd2a-11e4-838f-ccf56c9ba504.png)

**Comment by longgeek** [comment]
需要单独为 .conf 结尾文件加一个判断。
返回：已保存之类。

**Comment by longgeek** [comment]
Fixed Bug：

```
http://review.pyindex.com/#/c/1681/
```
