### ISSUE TITLE
docker 和  looker  提示优化 @xcluo

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#188]
![image](https://cloud.githubusercontent.com/assets/1789545/7017750/b3ac90ae-dd2e-11e4-8d68-66007a4b343e.png)

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

![image](https://cloud.githubusercontent.com/assets/1789545/7017757/c158e4a0-dd2e-11e4-8952-4d1b51eb7584.png)

**Comment by hajifish** [comment]
怎么搞？是looker判定为非200都显示一个错误提示，比如：“Cloud can not boot, refresh browse or start course again!"，还是你 TP 或 MT 那边把消息处理了我在显示？ 得找个合理的 reason.....oa

**Comment by longgeek** [comment]
需要先列出都有哪些常见的错误：
1. Container 没有运行
2. Container 不存在
3. Timeout （网络延迟、负载高或后端挂掉了都会出现 Timeout）

**Comment by longgeek** [comment]
Looker 那边可以 try 嵌套一个 try，当出现错误，重新尝试发消息，还不行就抛出错误。

**Comment by hajifish** [comment]
那最多try一次，并且这样很ugly ，按正常，应该是一次告诉他，除非用户自己的网络问题。

你提的那几个倒是不错， 三个层次，你们 TP 或 MT 能返回这样的结果吗？

------------------ Original ------------------

**Comment by longgeek** [comment]
不一定都是 TP 或 MT 会返回，有时候可能 CR 会返回。

**Comment by hajifish** [comment]
Done 采用一句话方式先。
