### ISSUE TITLE
选择题设计

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#190]
![6](https://cloud.githubusercontent.com/assets/1789545/7017949/4615c99a-dd31-11e4-80bc-4485d2c0dc47.png)

**Comment by longgeek** [comment]
@xcluo 根据目前的反馈来看，主要问题集中在两点:
1. 做题时候 Dot 和箭头太小，不好点击
2. 显示正确和错误答案是用 hover 事件，会显得乱

关于第一个问题比较好解决，主要是结果展示问题，可否用弹出框方式？？如下图，直接说出他的答案，和正确答案。其它题型也可使用这种方式。

![image](https://cloud.githubusercontent.com/assets/2102615/7081583/ea782784-df76-11e4-9555-fd4fbdea2f8a.png)

![image](https://cloud.githubusercontent.com/assets/2102615/7081587/13245202-df77-11e4-8263-9ced69b5349d.png)

**Comment by hajifish** [comment]
这个设计很好，需要考虑这个弹出框怎么适应：做错了，做对了，对了还能看题目吗，错了怎么看题目，看了能重做不？不想重做怎么办。。。

第二个问题和第一个我的疑问是有很大关联的，如果解决好新的显示问题，第二个也就不存在问题了，可能需要重新设计个样式。

------------------ Original ------------------

**Comment by longgeek** [comment]
比如选择题：
1. 做错了，点击空白地方，可直接关闭弹出框，或者加个 close 按钮，在或者来个 x 按钮，关闭弹出框后界面不变化，还是保留用户已选择的数据，可以继续提交

![image](https://cloud.githubusercontent.com/assets/2102615/7082371/dd06d4ec-df85-11e4-973b-48b0a4f5dd4a.png)
1. 做对了，同样关闭弹出框后界面不变化，还可以继续提交

![image](https://cloud.githubusercontent.com/assets/2102615/7082425/86517cf0-df86-11e4-8663-cfb303a02637.png)

不想重做了可以点击 Dot 按钮来跳转。

**Comment by longgeek** [comment]
等待新界面设计，最终确定选择题的设计，暂时关闭。
