### ISSUE TITLE
[Looker]问问题系统升级

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#193]
@THSTACK/owners  大家讨论下吧，具体问问系统还有那些不足？

**Comment by baoyiluo** [comment]
前期实时性要求不需要太高，主要要有有效的回答。半个小时能给回复我觉得就可以，当然越快越好了！

**Comment by longgeek** [comment]
![image](https://cloud.githubusercontent.com/assets/2102615/7037871/31cec4fe-dddc-11e4-8f82-dd303da5ffd8.png)
1. i18n
2. Save 是什么？Save 里输入的内容是 Title？
3. Save 提交以后，Submit 里输入的是 Content？

**Comment by hajifish** [comment]
No, 真实用户可不是这么想的，看看 qq history,  我的评论 #177
