### ISSUE TITLE
[Looker]前端题技术论证

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#198]
前端题技术论证

**Comment by baoyiluo** [comment]
是采用web服务器，然后将前端代码打到静态文件中去，像 .html,.css,.js。还是采用django。将前端代码发送给后台，在由后台生成对应界面返回呢？ @All 讨论下！

**Comment by baoyiluo** [comment]
w3c采用的后者，就没有单独的css 、js文件了

**Comment by hajifish** [comment]
后者能在详细介绍下吗？ @baoyiluo  另外，现在的方式因该是你描述的第一种 @longgeek ？ 现在是怎么处理诸如： 文件名在 web的显示， html 如何映入， 多个js文件的有没有问题？

**Comment by longgeek** [comment]
@baoyiluo 用户的任何一个操作都要由后台去生成界面，后台服务器请求量也太大了吧。

**Comment by baoyiluo** [comment]
@xcluo 后者就是直接把用户输入的html代码提交给后台，然后返回生成界面！

**Comment by hajifish** [comment]
结果：
  使用现有方式，但是需要注意目录和docker那边的处理流程。 还需要在实际环境试验下，正好这周前端题上线，测测。 @almasgeek 现在负责，@baoyiluo 协助。
