### ISSUE TITLE
工单能在个人设置中查看。

### ISSUE THREAD

**Issue by vincenthe11** [longgeek/bug-report#201]
1、现在工单只能在某个问题的页面中查看，如果不在此学习的界面，就会无法查看到此工单的回复。
只有回复了才能查看工单。
没有统一工单列表预览。
![2](https://cloud.githubusercontent.com/assets/8400716/7101961/a0380e4a-e0a3-11e4-9264-88c42ba522a6.jpg)
![3](https://cloud.githubusercontent.com/assets/8400716/7101962/a14cabe2-e0a3-11e4-9db7-4b46ca02204c.jpg)

2、工单回复2个之后无法submit。
![bug](https://cloud.githubusercontent.com/assets/8400716/7101957/79adb46e-e0a3-11e4-98ad-047bd51e8ccd.jpg)

**Comment by longgeek** [comment]
@baoyiluo
------------------ Original ------------------

**Comment by vincenthe11** [comment]
@baoyiluo  更新，看到工单列表了。
submit有效了，我再测测。
把工单放到个人设置中让用户可以查看到把

**Comment by hajifish** [comment]
@baoyiluo 位置调整到  ME下面， 现在Me下面删除了 Message, 可以用 工单补上。如何？

**Comment by baoyiluo** [comment]
@xcluo 问题不和账账单放一起了？不是说整合到一个界面吗？

**Comment by baoyiluo** [comment]
工单类型， 个人问题。功能丰富

**Comment by hajifish** [comment]
不放一块。

**Comment by baoyiluo** [comment]
http://review.pyindex.com/#/c/1754/
