### ISSUE TITLE
[Looker 长时间不学习，重新进入bug]

### ISSUE THREAD

**Issue by baoyiluo** [longgeek/bug-report#202]
![2015-04-13 2 57 22](https://cloud.githubusercontent.com/assets/2637585/7111108/ee801f84-e1ed-11e4-823e-2c36d4ca8f33.png)
![2015-04-13 2 57 37](https://cloud.githubusercontent.com/assets/2637585/7111114/fb3aa960-e1ed-11e4-815b-0a62a423fe24.png)

![2015-04-13 2 57 22](https://cloud.githubusercontent.com/assets/2637585/7111108/ee801f84-e1ed-11e4-823e-2c36d4ca8f33.png)

**Comment by hajifish** [comment]
received!

**Comment by hajifish** [comment]
Done
