### ISSUE TITLE
语言纠正(allspark国际化)

### ISSUE THREAD

**Issue by Yxnt** [longgeek/bug-report#204]
在更改界面语言时还是有些内容会显示中文，例如账单那里还是会显示软件工程师

**Comment by longgeek** [comment]
已确认，感谢反馈。

![image](https://cloud.githubusercontent.com/assets/2102615/7130338/36be319c-e2a1-11e4-8c98-35c765061373.png)

**Comment by hajifish** [comment]
系统是中英文的， 但是课程是中文的， 英文会专门有英文的课程。所以课程中的语言不能修改，你提到的提示是可以改的，以及确认，处理中。  谢谢！

------------------ Original ------------------

**Comment by hajifish** [comment]
Done
