### ISSUE TITLE
建议：

### ISSUE THREAD

**Issue by Yxnt** [longgeek/bug-report#205]
1. 用户学习完课程后把图标加上进度100%
2. 关于rm -rf / 虽然ubuntu是有保护的，可是用户添加参数后依旧可以删除，建议在首页或帮助页面给一个具体说明。

**Comment by longgeek** [comment]
非常感谢，已收到你的反馈，待确认后我们会进一步添加它。 
------------------ Original ------------------

**Comment by Yxnt** [comment]
- \- 还有个建议，vim 那里，关于分屏 按下ctrl+w 会关闭浏览器，，，按键冲突

**Comment by longgeek** [comment]
你是用的什么浏览器呢？按键的时候焦点在 vim 中吗？ 
------------------ Original ------------------

**Comment by Yxnt** [comment]
用的chrome，按键的时候焦点是在vim里面的。

**Comment by longgeek** [comment]
@Yxnt 你是 windows 系统吗？

**Comment by Yxnt** [comment]
是的- - ， 公司机器是win，笔记本是opensuse 还没有尝试， 但是现在绝大部分小伙伴都是windows。

**Comment by longgeek** [comment]
ok, 已确认在 windows、ubuntu 下会出现这种情况，再次感谢。

**Comment by Yxnt** [comment]
待我去opensuse下试试， 

-.-

**Comment by longgeek** [comment]
@Yxnt OK

**Comment by Yxnt** [comment]
测试结果如下：
OS：OpenSuse
浏览器：Firefox
结果：支持vim分屏功能
OS：OpenSuse
浏览器：Chrome
结果：Ctrl+W 关闭当前页面。。
莫非是Chrome的事情- -。。。

**Comment by longgeek** [comment]
不是，mac 下正常，应该需要调整 j s 
------------------ Original ------------------

**Comment by Yxnt** [comment]
soga。

**Comment by hajifish** [comment]
第一个问题： 100% 已经有了，只是个别浏览器不显示  100% 的那个 对号。 我找人来调试。
第二个问题：rm -rf / 怎么处理？

**Comment by longgeek** [comment]
针对 -f 参数做一下解释, 在针对 centos 和 ubuntu 对 rm -fr / 的处理简单说明一下。

**Comment by hajifish** [comment]
现在的情况：
  第一个问题：@almasgeek 解决，暂没完成；
  第二个问题： 在处理中 @longgeek

**Comment by longgeek** [comment]
再次测试，chrome 在 windows、ubuntu 下使用 [Ctrl] + [w] 都会关闭浏览器，暂时没有办法。

**Comment by longgeek** [comment]
已解释 -f、-i 参数。

![image](https://cloud.githubusercontent.com/assets/2102615/7643340/3f656d1e-facb-11e4-9bae-7a1669a51ae6.png)
