### ISSUE TITLE
looker study 终端的bug (不显示shell，只显示ipython)

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#206]
![image](https://cloud.githubusercontent.com/assets/1789545/7156226/62f7922a-e397-11e4-9e43-81017f726975.png)

@xcluo 协助解决

**Comment by longgeek** [comment]
@xcluo 正在定位具体的问题。

**Comment by longgeek** [comment]
在 ipython 题中，去掉了获取 bash 的 url，已经 merge 到线上系统，还需测试，看有无用户在出现这种情况.

**Comment by hajifish** [comment]
问题重现，：

start  页面不要 继续，直接 从第九章 最后一节开始，然后正常调入下一章（第10章），打开终端就出现这个问题了。

**Comment by hajifish** [comment]
Done same as #238
