### ISSUE TITLE
刚注册的用户点击开始学习跳转到console的页面后就跳转回来了。

### ISSUE THREAD

**Issue by ghost** [longgeek/bug-report#207]
如题。
浏览器：chrome 41.0.2272.118m       win7  x64

刚注册后点击开始答题，
能看到 bash页面一下就自动跳回 开始学习页面了。
注销后重新登录 就可以了。。

**Comment by longgeek** [comment]
已收到反馈，我们会尽快定位问题所在、并解决。

**Comment by hajifish** [comment]
Got it, processing now.

**Comment by baoyiluo** [comment]
http://review.pyindex.com/#/c/1764/

**Comment by hajifish** [comment]
问题找到(tks @longgeek )，注册后登陆和登陆代码逻辑不一致。@baoyiluo fixed it.
