### ISSUE TITLE
课程中增加 req.write() 输出中文的支持。

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#208]

**Comment by longgeek** [comment]
需要先定位问题.

**Comment by longgeek** [comment]
找到问题，Python 字符集转换一下就 ok。

```
from mod_python import apache
def handler(req):
    req.write(u"中文支持".encode('gbk'))
    return apache.OK
```

**Comment by hajifish** [comment]
Good job, very well.......

------------------ Original ------------------

**Comment by longgeek** [comment]
已加入代码到文档.

![image](https://cloud.githubusercontent.com/assets/2102615/7213799/50d3d742-e5be-11e4-9aad-c7fac9eee884.png)

**Comment by hajifish** [comment]
gbk?    浏览器要是不是gbk怎么吧。

------------------ Original ------------------
