### ISSUE TITLE
添加新题型：考虑增加一个 Agenda 题型

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#211]
每个Stage 的开始有个简介，再有个  大纲 貌似更好一点。就像PPT 一般第二页有个 agenda.

@longgeek @baoyiluo @almasgeek  发表下看法。

**Comment by longgeek** [comment]
开始介绍 + 最后总结，可能对于整个课程结构感觉更清晰一点。

**Comment by hajifish** [comment]
最后总结怎么展示？ 也用 Agenda题型，还是其他？

------------------ Original ------------------

**Comment by hajifish** [comment]
?

**Comment by hajifish** [comment]
需求不明显

**Comment by longgeek** [comment]
需求还是比较明显的，我在录题时候，也能感觉到，用户估计更强烈点。

开始介绍，可以搞个类似目录结构。
最后总结，加到长条里，只有左边的 docs，在 boss 中可以录。

**Comment by longgeek** [comment]
Fixed:

```
http://review.pyindex.com/#/c/1919/
http://review.pyindex.com/#/c/1918/
http://review.pyindex.com/#/c/1920/
```
