### ISSUE TITLE
工单新建，回复时间都是UTC时间。

### ISSUE THREAD

**Issue by vincenthe11** [longgeek/bug-report#213]
应该换算成本地北京时间。
![image](https://cloud.githubusercontent.com/assets/8400716/7215491/aa8e36f2-e60d-11e4-861e-4e0249f037b4.png)

**Comment by hajifish** [comment]
已确认，修改中。

------------------ Original ------------------

**Comment by longgeek** [comment]
@almasgeek

**Comment by hajifish** [comment]
怎么解决的？

------------------ Original ------------------
