### ISSUE TITLE
代码题目录设计

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#222]
@xcluo

**Comment by longgeek** [comment]
需要回顾以前代码，看看有哪些依赖。
大致结构:
coursename/partname-number/stagename-number/taskname-number/

**Comment by hajifish** [comment]
partname/stagename/taskname all is Chinese.

------------------ Original ------------------

**Comment by longgeek** [comment]
1. 以 part 名字为入口的话，part 会越来越多，用户在自己看的时候很难找到入口。
2. 如果用中文的话，用户通过我们的 console 是没有办法 cd 进去的，不支持中文输入法，所以最好还是用英文。

**Comment by longgeek** [comment]
现在的一个问题：Ashinamo 项目既是一个单独的课程，又是在 Python 课程里的多个章，目录如何分配？
1. 项目：/pythonpie/project/ashinamo
2. 课程：/pythonpie/course/course_name/part_name/{Custom dir or file names}

@xcluo right?

**Comment by hajifish** [comment]
No:
1. 项目中：  /pythonpie/project/ashinamo/
2. 课程中： /pythonpie/course/<Course Name>/ashinamo

这样方便文件引入，因为项目的项目目录，必须永远在一个地方，方便文件引入。

另外，这样他完成课程后，想再做一次项目，也不会和课程冲突，可以重现做一次。

**Comment by longgeek** [comment]
其它的课程题都是在 /pythonpie/course/course_name/part_name/{Custom dir or file names} 这个路径下，但是 Ashinamo 的题是在 /pythonpie/course//ashinamo 问题就会出现：

我需要在代码题和 Django 题里自动为普通题添加 /pythonpie/course/course_name/part_name 这个路径，但这样就造成所有的题都会在 /pythonpie/course/course_name/part_name 目录下。

所以应该在录题时候添加一个字段来作为判断依据。

**Comment by longgeek** [comment]
后台应该添加一个 checkbox，是否使用默认路径？
- 不使用默认路径的话，需要在后台手工录入路径：/ashinamo/ashinamo/settings.py
- 使用默认路径的话，完整的路径应该是: /pythonpie/course/course_name/part_name/{Custom dir or file names}

**Comment by longgeek** [comment]
Fixed:

```
http://review.pyindex.com/#/c/2019/
http://review.pyindex.com/#/c/2020/
http://review.pyindex.com/#/c/2021/
```

**Comment by longgeek** [comment]
合并后，只需要修改代码题需要使用绝对路径的题，在后台把 checkbox 勾上就可以。
