### ISSUE TITLE
题目问题（for循环这边)

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#224]
![image](https://cloud.githubusercontent.com/assets/1789545/7232666/83d06abe-e7af-11e4-8346-23799d2079db.png)

改完后截个图发这里，如果是 @almasgeek 的，分给他。

**Comment by hajifish** [comment]
对了，整体看看在有啥问题没有，如果不是almas的，你就fix了

**Comment by baoyiluo** [comment]
fixed
