### ISSUE TITLE
经常会出现奔溃，会话丢失

### ISSUE THREAD

**Issue by by001** [longgeek/bug-report#226]
到了第9章以后，经常会出现会话丢失的情况，还有会出现点击got it 没反应的情况。

**Comment by longgeek** [comment]
这是一个历史遗留下来的问题，在技术上有很大的挑战，比较影响用户体验，
我们会在近期讨论这个问题，非常感谢。

**Comment by hajifish** [comment]
Done，暂时优化 zion 的 disconnect_timeout参数，跳到 5000+
