### ISSUE TITLE
小问题纠正

### ISSUE THREAD

**Issue by Yxnt** [longgeek/bug-report#227]
第五章：数据类型--整形
在左侧文档最下方“需求/问题”中提示“完成后点击保存并执行” 在右侧的终端中只有GOT it

注：莫怪我火眼金睛^_^

![qq 20150425153016](https://cloud.githubusercontent.com/assets/10323352/7332062/039c1898-eb60-11e4-9ee6-592a29b74a23.png)

**Comment by hajifish** [comment]
点赞！ NB啊，马上去 fixed.

------------------ Original ------------------

**Comment by Yxnt** [comment]
- \- 好像第5章都是这样滴。目前只学到第五章正在慢慢学。

**Comment by longgeek** [comment]
赞！

**Comment by hajifish** [comment]
Done,  整个一节都改了，但是整个章的其他部分没问题。
