### ISSUE TITLE
[NewBoss] 创建/修改 Part的时候，tag可以从现有的tag中选择一个。

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#230]
![image](https://cloud.githubusercontent.com/assets/1789545/7354051/fd376588-ed4a-11e4-97a3-4a4cafdf91b8.png)

**Comment by CodeAlmas** [comment]
color_admin_v1.4/admin/template_content/form_plugins.html

![screenshot from 2015-05-11 18 55 18](https://cloud.githubusercontent.com/assets/8491535/7563399/61782b26-f80f-11e4-992d-9478f3e289a9.png)

**Comment by hajifish** [comment]
可以这样搞：

allspark/apphome/model/settings 中有个配置叫： TECH

可以用它的 get_XXX_display 生成，比如 python 可以生成：

Python入门，Python深入，Python高级..

**Comment by hajifish** [comment]
delay
