### ISSUE TITLE
忘记密码的链接有效期是 30 分钟还是 10 分钟？

### ISSUE THREAD

**Issue by longgeek** [longgeek/bug-report#233]
这个显示的是 30 分钟：
![image](https://cloud.githubusercontent.com/assets/2102615/7576627/6b14d7f2-f872-11e4-8bda-908ad5c7b185.png)

而收到邮件是 10 分钟：
![image](https://cloud.githubusercontent.com/assets/2102615/7576636/87a97db4-f872-11e4-85e1-6896fd7cb424.png)

请确认，并修改.

**Comment by hajifish** [comment]
@baoyiluo

**Comment by baoyiluo** [comment]
我看下！

**Comment by baoyiluo** [comment]
http://review.pyindex.com/#/c/1892/
