### ISSUE TITLE
添加新题型：总结页面

### ISSUE THREAD

**Issue by longgeek** [longgeek/bug-report#244]
1. 回顾本节所学习的内容。
2. 是否需要展示统计信息？
- 本节学习时长
- 本节花费情况
1. 怎么和本节完、本章完页面结合？

**Comment by hajifish** [comment]
本节花费没办法做，必须是用户退出学习，才能拿到 花费的数据， 所以时长也无法统计。

总结，主要还是总结学到到什么，下面会学到什么，已经本节的重点是什么， 还是偏学习内容方面的总结。

**Comment by longgeek** [comment]
考虑下怎么展示和本章完怎么结合。

**Comment by hajifish** [comment]
Well

**Comment by longgeek** [comment]
应该类似 main
![image](https://cloud.githubusercontent.com/assets/2102615/7991842/bf50f238-0b2d-11e5-811b-5c5f34bf6743.png)

**Comment by longgeek** [comment]
Fixed:

```
http://review.pyindex.com/#/c/1954/
http://review.pyindex.com/#/c/1955/
http://review.pyindex.com/#/c/1956/
```
