### ISSUE TITLE
添加新题型：Django 代码题

### ISSUE THREAD

**Issue by longgeek** [longgeek/bug-report#245]
目前有以下需求：
- 当跳转到 Django 题后，如果用户没执行 runserver，则程序自动执行 runserver。
- 自动检测项目是否存在，不存在创建项目，并同步文件内容。

后台如何录入数据？
- 需要一个创建项目按钮、可以指定创建的路径
- ... 待续

**Comment by hajifish** [comment]
自动创建项目？这个可以不要吧，大多数情况时录好题，让座。 你说的自动创建项目，应该是载入题目的时候，自动吧项目文件写到目录吧？

**Comment by longgeek** [comment]
@xcluo 录题时候应该有个选项，可以创建一个项目，或者引用一个项目。但用户有可能删掉这个项目，那代码里应该去判断该项目是否存在，不存在则用 django 创建项目。

ps: 后台录制内容的时候，可能只录制少数 django 文件。

**Comment by hajifish** [comment]
引用可能不现实，有版本问题，必须创建，然后录的时候，创建完项目，直接把所有文件放数据库。

用户只需要复制文件到container 即可，不能再调用命令创建 django project， 又可能，录的时候的版本和 用户自己的 django 版本不一致。

**Comment by longgeek** [comment]
再次罗列下需求：
1. 后台有对应的 django 版本选择器，在学习题的时候，自动使用对应 django 版本，判断项目是否存在，则创建项目。
2. django 自动创建项目，提供了默认的一些文件，而有些默认文件需要做一些修改，但是在学习界面并不显示，考虑加一个字段：default-files, 这个字段可以录入文件和内容，而现在的 code-files 录入的文件和内容才会展示到学习界面中。
3. 学习界面自动根据 django 版本，启动 runserver。

**Comment by longgeek** [comment]
Fixed:

```
http://review.pyindex.com/#/c/2007/
http://review.pyindex.com/#/c/2008/
http://review.pyindex.com/#/c/2009/
http://review.pyindex.com/#/c/2010/
http://review.pyindex.com/#/c/2011/
http://review.pyindex.com/#/c/2012/
```

**Comment by longgeek** [comment]
当后台录入一个空内容的文件时候，不需要覆盖生成的文件内容。

```
http://review.pyindex.com/#/c/2014/
```
