### ISSUE TITLE
问题描述不明确

### ISSUE THREAD

**Issue by Yxnt** [longgeek/bug-report#247]
![image](https://cloud.githubusercontent.com/assets/10323352/7696037/1c1cf206-fe2b-11e4-84ac-e7fc27cf6366.png)
我想知道问题真的要这么提问比较好么- -，

**Comment by Yxnt** [comment]
![image](https://cloud.githubusercontent.com/assets/10323352/7696205/742e4dda-fe2d-11e4-93ba-08a11448d868.png)
这个情况前面提到过一次，这次是第七章的。好好检查一下咯

**Comment by longgeek** [comment]
感谢反馈，现在课程还不完善，待课程全部开放后，我们会重新修正几遍整个课程内容，争取做到没有瑕疵。
