### ISSUE TITLE
[Boss] 充值卡

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#252]
![qq20150602-3](https://cloud.githubusercontent.com/assets/1789545/7932040/ed57d09e-0947-11e5-9b4d-3790c6eddc38.jpg)

**Comment by hajifish** [comment]
都测试下，另外几个功能也有问题。

**Comment by longgeek** [comment]
Fixed:

```
http://review.pyindex.com/#/c/2082
```
