### ISSUE TITLE
Django 题的 XFrameOptions 问题

### ISSUE THREAD

**Issue by longgeek** [longgeek/bug-report#281]
如果是用户自己创建的项目，使用 Django 题查看 web 时候，会无法显示。

解决办法：
1. virtualenv 中的 Django 命令加入到环境变量
2. 让用户自己修改
3. Django 题自己去处理、修改。
4. Django 题后台录制 settings.py 默认去掉 XFrameOptions

**Comment by hajifish** [comment]
不是特别明白@longgeek

**Comment by longgeek** [comment]
@xcluo 比如 Ashinamo 项目：

项目是用户自己用 bash 命令去创建的，而创建 `django-admin.py` 命令是用户自己用 `pip` 安装的，所以创建的任何项目中的 `settings.py` 文件默认开启了 `XFramOptinos` 选项，在 Django 题的时候：就会造成我们的 iframe 无法加载项目的 Web

**Comment by longgeek** [comment]
我们的 Django 题使用的是 virtualenv 中的 Django，而它是挂载到容器中的，事先我改了源码，注释掉了 `XFramOptinos` 选项。

**Comment by hajifish** [comment]
为什么要注掉它呢？

**Comment by longgeek** [comment]
不注释掉，iframe 无法加载。

**Comment by longgeek** [comment]
尝试采用第三种方式。

**Comment by longgeek** [comment]
Fixed：

```
http://review.pyindex.com/#/c/2078
```

**Comment by hajifish** [comment]
Done
