### ISSUE TITLE
Django 题的 Web 展示需要手工指定路径

### ISSUE THREAD

**Issue by longgeek** [longgeek/bug-report#282]
默认是在首页，暂时无法指定路径，需要一个输入框，可以跳转路径。

**Comment by hajifish** [comment]
比如？

**Comment by longgeek** [comment]
@xcluo Django 题有两个必须要显示的窗口：
1. runserver
2. web 

但是后期我们会为项目写一些 url 路径，用户需要去测试某一个路径，那他现在是没有在 2. web 界面上指定路径的，因为默认就是访问的 :8000 也就是首页。

先在加了新标签中显示，所以考虑要不要添加这个指定路径功能。
