### ISSUE TITLE
项目题型

### ISSUE THREAD

**Issue by longgeek** [longgeek/bug-report#288]
@xcluo 任务说明、技术分析... 这些一般是没有左侧的文档，考虑是否直接全屏。

**Comment by hajifish** [comment]
建议新界面设计成全屏，理由如下；
1. 如果采用 MVVM，渲染放到前端，那么不存在Django渲染的时候，页面出现缓慢变化的问题，使得用户“感受不到页面变化的过程”，而现在Django渲染，页面大的变化的时候，浏览器需要Ajax加载数据，加载完后还需要 set_windows....
2. 另外，技术分析，任务说明，不应该纯文档展示，一来很多人不一定耐心看下去，到止编码的时候一堆没必要问的问题，二来，现有choice,fillin等题型，可以适当保障用户对于 reading  的质量。 

建议，不仅仅改全屏，还要结合 choice, filling, 等手段，提供读，和保障必须读的可能。另外还需区别，“没必要必须读”的可能......

**Comment by longgeek** [comment]
先采用了总结题。
