### ISSUE TITLE
有个想法：

### ISSUE THREAD

**Issue by hajifish** [longgeek/bug-report#300]
如果用户在一个虚拟机中，学完Python，想体验下 openstack, 那么能不能通过 映入文件 .venv + devstack 的方式，在当前虚拟机下学习呢？这样就不需要多个虚拟机，也免的我们架构和计费复杂化。

**Comment by longgeek** [comment]
用户的多个 vm，是必然的，这样弄也是一个办法，但我想直接做一个 livestack 的镜像，直接启动镜像，openstack 环境就有了。

也可以弄一个 devestack 的镜像。

**Comment by hajifish** [comment]
Multi VMs design well.

```
1. Image-based request looks more like the Cloud behaviors;
2. Nonexistence one to match every flavor, because of online course/project/plan start with different quota requirement.
```
